export const RO = {
  nav: {
    dashboard: 'Panou Principal',
    clients: 'Clienți',
    products: 'Produse',
    orders: 'Comenzi',
    reports: 'Rapoarte',
    settings: 'Setări',
  },
  common: {
    search: 'Caută...',
    add: 'Adaugă',
    edit: 'Editează',
    save: 'Salvează',
    cancel: 'Anulează',
    confirm: 'Confirmă',
    delete: 'Șterge',
    deactivate: 'Dezactivează',
    activate: 'Activează',
    back: 'Înapoi',
    loading: 'Se încarcă...',
    noData: 'Nu există date',
    actions: 'Acțiuni',
    status: 'Status',
    active: 'Activ',
    inactive: 'Inactiv',
    yes: 'Da',
    no: 'Nu',
    areYouSure: 'Ești sigur?',
    logout: 'Deconectare',
  },
  pagination: {
    previous: 'Anterior',
    next: 'Următorul',
    showing: 'Afișare',
    of: 'din',
    results: 'rezultate',
  },
  products: {
    title: 'Produse',
    add: 'Adaugă Produs',
    name: 'Nume',
    sku: 'Cod SKU',
    category: 'Categorie',
    sellPrice: 'Preț Vânzare',
    costPrice: 'Preț Achiziție',
    margin: 'Marjă %',
    stock: 'Stoc',
    description: 'Descriere',
    categories: ['Materiale Compozite', 'Instrumente', 'Consumabile', 'Implanturi'] as const,
  },
  clients: {
    title: 'Clienți',
    add: 'Adaugă Client',
    company: 'Companie',
    contact: 'Persoană Contact',
    city: 'Oraș',
    email: 'Email',
    phone: 'Telefon',
    address: 'Adresă',
    discount: 'Discount %',
    creditLimit: 'Limită Credit',
    paymentTerms: 'Termen Plată (zile)',
    notes: 'Notițe',
    totalSpent: 'Total Cheltuit',
    outstanding: 'Sold Restant',
    avgOrder: 'Valoare Medie Comandă',
    profitMargin: 'Marjă Profitabilitate',
  },
  orders: {
    title: 'Comenzi',
    add: 'Comandă Nouă',
    number: 'Nr. Comandă',
    client: 'Client',
    date: 'Dată',
    total: 'Total',
    paid: 'Plătit',
    balance: 'Sold',
    pending: 'În așteptare',
    delivered: 'Livrată',
    cancelled: 'Anulată',
    product: 'Produs',
    quantity: 'Cantitate',
    unitPrice: 'Preț Unitar',
    clientDiscount: 'Discount Client',
    rowTotal: 'Total Rând',
    markPayment: 'Marchează Plata',
    confirm: 'Confirmă Comanda',
    tva: 'TVA 19%',
    totalWithTva: 'Total cu TVA',
  },
  offers: {
    generate: 'Generează Ofertă',
    title: 'Ofertă pentru',
    anchor: 'Ancoră',
    upsell: 'Upsell',
    totalOffer: 'Total Ofertă',
    avgMargin: 'Marjă Medie',
    edit: 'Editează',
    regenerate: 'Regenerează',
    aiInsight: 'Recomandare AI',
  },
  reports: {
    title: 'Rapoarte',
    profitability: 'Profitabilitate Clienți',
    products: 'Performanță Produse',
    topSellers: 'Top Vânzări',
    slowMovers: 'Mișcare Lentă',
    revenue: 'Venituri',
    cost: 'Cost',
    profit: 'Profit',
    unitsSold: 'Unități Vândute',
    uniqueClients: 'Clienți Unici',
    salesVelocity: 'Viteză Vânzare',
  },
  dashboard: {
    title: 'Panou Principal',
    revenueThisMonth: 'Venituri Luna Aceasta',
    ordersThisMonth: 'Comenzi',
    activeClients: 'Clienți Activi',
    outstandingPayments: 'Plăți Restante',
    topClients: 'Top Clienți',
    slowMovers: 'Produse cu Mișcare Lentă',
    recentOrders: 'Comenzi Recente',
  },
  settings: {
    title: 'Setări',
    account: 'Cont',
    changePassword: 'Schimbă Parola',
    currentPassword: 'Parolă Curentă',
    newPassword: 'Parolă Nouă',
    confirmPassword: 'Confirmă Parola',
    engineConfig: 'Configurare Motor Oferte',
    clientFrequency: 'Frecvență Client',
    globalPopularity: 'Popularitate Globală',
    margin: 'Marjă Profit',
    recency: 'Recență',
    slowMoverPush: 'Mișcare Lentă',
    totalWeights: 'Total Ponderi',
    anchorRatio: 'Raport Ancoră/Upsell',
    minBundle: 'Dimensiune Minimă Ofertă',
    maxBundle: 'Dimensiune Maximă Ofertă',
    categoryLimit: 'Limită Categorie',
    scoringPeriod: 'Perioadă Analiză (zile)',
  },
} as const
